services:
  postgres:
    image: postgres:16
    container_name: stocker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: stocker-redis
    ports:
      - '6379:6379'

volumes:
  postgres_data: